devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),

]

urlpatterns += static( settings.MEDIA_URL, document_root= settings.MEDIA_ROOT )
urlpatterns += static( settings.STATIC_URL, document_root= settings.STATIC_ROOT )

projects/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.projects, name="projects"),
    path('project/<str:pk>/',views.project, name="project_name"),
    path('create-project/',views.createProject, name="create-project"),
    path('create-project/<str:pk>/',views.updateProject, name="update-project"),
    path('delete-project/<str:pk>/',views.deleteProject, name="delete-project")
]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),

    path('',views.profiles, name="profiles"),
    path('profile/<str:pk>/',views.userProfile, name='user-profile'),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile


# Create your models here.

class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, blank=True, null=True)
    source_link = models.CharField(max_length=2000, blank=True, null=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, blank=True, null=True)
    vote_ratio = models.IntegerField(default=0, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.title


class Reviews(models.Model):
    VOTE_TYPE = (
        ('up', 'up vote'),
        ('down', 'down vote'),
    )
    # owner =
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid



# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    locations = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    sort_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default='profiles/user-default.png')
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        # if user is avalable
        return str(self.username)  # wrap in str so we dont get any error


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    discription = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

projects/forms.py
from django.forms import ModelForm
from django import forms
from .models import Project

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = [
            'title',
            'description',
            'featured_image',
            'demo_link',
            'source_link',
            'tags',
        ]

        widgets = {
            'tags':forms.CheckboxSelectMultiple(),

        }

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

        # self.fields['title'].widget.attrs.update({'class':'input','placeholder':'Add Title'})

projects/views.py
from django.shortcuts import render, redirect
from .models import Project, Reviews, Tag
from .forms import ProjectForm
from django.contrib.auth.decorators import login_required
# Create your views here.



# sending a http responce
def projects(request):
    all_projects = Project.objects.all()
    context = {'projects':all_projects}
    
    return render(request, 'projects/projects.html',context)

def project(request, pk):
    project_obj = Project.objects.get(id = pk)
    tags = project_obj.tags.all()
    context = {
        'p_obj': project_obj,
    }
    return render(request, 'projects/single-project.html',context)

@login_required(login_url='login')
def createProject(request):
    form = ProjectForm()

    if request.method == "POST":
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('projects')

    context = {'form': form}
    return render(request, 'projects/project_form.html', context)

@login_required(login_url='login')
def updateProject(request, pk):
    project_obj = Project.objects.get(id = pk)
    form = ProjectForm(instance=project_obj)

    if request.method == "POST":
        form = ProjectForm(request.POST,request.FILES, instance=project_obj)
        if form.is_valid():
            form.save()
            return redirect('projects')
    context = {'form': form}
    return render(request, 'projects/project_form.html', context)

@login_required(login_url='login')
def deleteProject(request, pk):
    project_obj = Project.objects.get(id = pk)

    if request.method == "POST":
        project_obj.delete()
        return redirect('projects')
    
    context = {'object': project_obj}

    return render(request, 'projects/delete-confirm.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Profile


def loginUser(request):

    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username = username)
        except:
            messages.error(request,'username does not exits')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request,'username or password is incorrect')


    return render(request, 'users/login_register.html')

def logoutUser(request):
    logout(request)
    messages.success(request, 'user is successfully logged out!!')
    return redirect('login')

def profiles(request):
    profiles = Profile.objects.all()
    context = {
        'profiles': profiles,
    }
    return render(request, 'users/profile.html', context)


def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)
    context = {
        'user': profile,
    }
    return render(request, 'users/user-profile.html', context)

projects/templates/projects/delete-confirm.html
{% extends 'main.html' %}
{% block content%}
    <form action="" method="POST">
        {% csrf_token %}
        <h1>Are you sure you Want to delete {{object.title}} ?</h1>
        <a href="{% url 'projects' %}">go back</a>
        <input type="submit" value="confirm">
    </form>
{% endblock%}

projects/templates/projects/project_form.html
{% extends 'main.html' %}
{% block content%}
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{%url 'projects'%}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    {%for field in form%}
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">{{field.label}}: </label>
                        {{field}}
                    </div>
                    {%endfor%}
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
{% endblock%}

projects/templates/projects/projects.html
{% extends 'main.html' %}
{% block content %}

    <!-- Main Section -->
    <main class="projects">
    <section class="hero-section text-center">
        <div class="container container--narrow">
        <div class="hero-section__box">
            <h2>Search for <span>Projects</span></h2>
        </div>

        <div class="hero-section__search">
            <form class="form" action="#" method="get">
            <div class="form__field">
                <label for="formInput#search">Search By Projects </label>
                <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by Project Title" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
            </form>
        </div>
        </div>
    </section>

    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">
            {%for i in projects%}
          <div class="column">
            <div class="card project">
              <a href="{% url 'project_name' i.id %}" class="project">
                <img class="project__thumbnail" src="{{i.featured_image.url}}" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">{{i.title}}</h3>
                  <p><a class="project__author" href="{%url 'user-profile' i.owner.id %}" >By {{i.owner.name}}</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">{{i.vote_ratio}}%</span>positive feedback({{i.vote_total}} Vote{{i.vote_total|pluralize:"s"}})
                  </p>
                  <div class="project__tags">
                    {% for tag in i.tags.all%}
                    <span class="tag tag--pill tag--main">
                      <small>{{tag}}</small>
                    </span>
                    {% endfor %}
                  </div>
                </div>
              </a>
            </div>
          </div>
          {%endfor%}

        </div>
      </div>
    </section>

  </main>

  {%endblock content%} 

projects/templates/projects/single-project.html
{% extends 'main.html' %}

{% block content %}

    <main class="singleProject my-md">
        <div class="container">
          <div class="layout">
            <div class="column column--1of3">
              <h3 class="singleProject__subtitle">Tools & Stacks</h3>
              <div class="singleProject__toolStack">
                {% for tag in p_obj.tags.all%}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{tag}}</small>
                </span>
                {% endfor %}
              </div>
              
              {% if p_obj.source_link%}
              <a class="singleProject__liveLink" href="{{p_obj.source_link}}" target="_blank">
                <i class="im im-external-link"></i>Source Code</a>
              {%endif%}
                <br>
              {% if p_obj.demo_link%}
              <a class="singleProject__liveLink" href="{{p_obj.demo_link}}" target="_blank">
                <i class="im im-external-link"></i>Live Demo</a>
              {%endif%}
            
            </div>
            <div class="column column--2of3">
              <img class="singleProject__preview" src="{{p_obj.featured_image.url}}" alt="portfolio thumbnail" />
              <a href="profile.html" class="singleProject__developer">Md. Shahriar Parvez</a>
              <h2 class="singleProject__title">{{p_obj.title}}</h2>
              <h3 class="singleProject__subtitle">About the Project</h3>
              <div class="singleProject__info">
                {{p_obj.description}}
            </div>
    
              <div class="comments">
                <h3 class="singleProject__subtitle">Feedback</h3>
                <h5 class="project--rating">
                  {{p_obj.vote_ratio}}% Postitive Feedback ({{p_obj.vote_total}} Vote{{p_obj.vote_total|pluralize:"s"}})
                </h5>
    
                <form class="form" action="#" method="POST">
                  <!-- Textarea -->
                  <div class="form__field">
                    <label for="formInput#textarea">Comments: </label>
                    <textarea class="input input--textarea" name="message" id="formInput#textarea"
                      placeholder="Write your comments here..."></textarea>
                  </div>
                  <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
                </form>
                <div class="commentList">
                  <div class="comment">
                    <a href="profile.html">
                      <img class="avatar avatar--md"
                        src="https://pbs.twimg.com/profile_images/1335382240931368961/b3wSZKj4_400x400.jpg" alt="user" />
                    </a>
                    <div class="comment__details">
                      <a href="profile.html" class="comment__author">Sulamita Ivanov</a>
                      <p class="comment__info">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit alias numquam perferendis
                        mollitia minus minima exercitationem possimus ab deserunt qui, soluta iusto doloribus eveniet
                        similique consequuntur ratione, dignissimos ut magni laborum quo.
                      </p>
                    </div>
                  </div>
                  <div class="comment">
                    <a href="profile.html">
                      <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/33843378" alt="user" />
                    </a>
                    <div class="comment__details">
                      <a href="profile.html" class="comment__author">Dennis Ivanov</a>
                      <p class="comment__info">
                        Consectetur adipisicing elit. Reprehenderit alias numquam perferendis mollitia minus minima
                        exercitationem possimus ab deserunt qui, ratione, dignissimos ut magni laborum quo.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
      </main>


{%endblock content%}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" />
  
    <title>DevSearch - Connect with Developers!</title>
</head>
<body>


    {% include 'navbar.html' %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block content%}

    {% endblock content %}


</body>
</html>

templates/navbar.html
{% load static %}

<!-- Header Section -->
<header class="header">
    <div class="container container--narrow">
        <a href="{% url 'profiles' %}" class="header__logo">
        <img src="{% static 'images/logo.svg'%}" alt="DevSearch Logo" />
        </a>
        <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
            <span>Menu</span>
            <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
            <li class="header__menuItem"><a href="{% url 'profiles' %}">Developers</a></li>
            <li class="header__menuItem"><a href="{% url 'projects' %}">Projects</a></li>
            <li class="header__menuItem"><a href="">Inbox</a></li>
            {% if request.user.is_authenticated %}
            <li class="header__menuItem"><a href="{% url 'create-project' %}">Add project</a></li>
            <li class="header__menuItem"><a href="{% url 'logout' %}" class="btn btn--sub">Logout</a></li>
            {% else %}
            <li class="header__menuItem"><a href="{% url 'login' %}" class="btn btn--sub">Login/Sign Up</a></li>
            {% endif %}
        </ul>
        </nav>
    </div>
</header>

users/templates/users/login_register.html
{% extends 'main.html' %}

{% block content%}

    <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username" />
        <input type="password" name="password" placeholder="Enter Password" />
        <input type="submit" value="Login" />
    </form>
    
{% endblock content%}

users/templates/users/profile.html
{%extends 'main.html'%}

{%block content%}

    <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">

          {% for profile in profiles %}
            <div class="column card">
                <div class="dev">
                  <a href="{% url 'user-profile' profile.id%}" class="card__body">
                    <div class="dev__profile">
                      <img class="avatar avatar--md" src="{{profile.profile_image.url}}" alt="image" />
                      <div class="dev__meta">
                        <h3>{{profile.name}}</h3>
                        <h5>{{profile.sort_intro|slice:"60"}}</h5>
                      </div>
                    </div>
                    <p class="dev__info">
                      {{profile.bio|slice:"150"}}
                    </p>

                    <div class="dev__skills">
                      {% for skill in profile.skill_set.all|slice:"5" %}
                      <span class="tag tag--pill tag--main">
                        <small>{{skill}}</small>
                      </span>
                    {%endfor%}
                    </div>
                  </a>
                </div>
              </div>

          {% endfor %}
      </div>
    </section>
  </main>

{%endblock%}

users/templates/users/user-profile.html
{%extends 'main.html'%}

{%block content%}


    <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{user.profile_image.url}}" />
              <h2 class="dev__name">{{user.name}}</h2>
              <p class="dev__title">{{user.sort_intro}}</p>
              <p class="dev__location">{{user.locations}}</p>
              <ul class="dev__social">
                {% if user.social_github%}
                <li>
                  <a title="Github" href="{{user.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {%endif%}

                {% if user.social_youtube%}
                <li>
                  <a title="Stackoverflow" href="{{user.social_youtube}}" target="_blank"><i class="im im-youtube"></i></a>
                </li>
                {%endif%}

                {% if user.social_twitter%}
                <li>
                  <a title="Twitter" href="{{user.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {%endif%}

                {% if user.social_linkedin%}
                <li>
                  <a title="LinkedIn" href="{{user.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {%endif%}

                {% if user.social_website%}
                <li>
                  <a title="Personal Website" href="{{user.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {%endif%}





              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
            {{user.bio}}
            </p>
          </div>

          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              {% for skill in user.skill_set.all%}
                {%if skill.discription%}
                  <div class="devSkill">
                    <h4 class="devSkill__title">{{skill.name}}</h4>
                    <p class="devSkill__info">
                      {{skill.discription}}
                    </p>
                  </div>
                {%endif%}
              {%endfor%}


              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">

                {% for skill in user.skill_set.all%}
                  {%if not skill.discription%}
                    <span class="tag tag--pill tag--sub tag--lg">
                      <small>{{skill.name}}</small>
                    </span>
                {%endif%}
              {%endfor%}
              </div>
            </div>
          </div>

          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

            {%for project in user.project_set.all%}
                <div class="column">
                <div class="card project">
                  <a href="{%url 'project_name' project.id%}" class="project">
                    <img class="project__thumbnail" src="{{project.featured_image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="{%url 'user-profile' user.id%}">{{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all%}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {%endfor%}
                      </div>
                    </div>
                  </a>
                </div>
              </div>

            {%endfor%}

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{%endblock content%}